### ISSUE TITLE
Gtk3's window.set_wmclass is deprecated

### ISSUE THREAD

**Issue by maimere** [biglinux/bigbashview#50]
As of version 3.22 of Gtk, method `Gtk.Window.set_wmclass` [is deprecated](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.set_wmclass), being used in lines [127](https://github.com/biglinux/bigbashview/blob/440163737f9bb58706a826b8c54ec97b88a39be2/bigbashview/usr/lib/python3/dist-packages/bbv/main.py#L127) and [147](https://github.com/biglinux/bigbashview/blob/440163737f9bb58706a826b8c54ec97b88a39be2/bigbashview/usr/lib/python3/dist-packages/bbv/main.py#L147) of `main.py`.

I would like to suggest the substitution of set_wmclass for set_role, [according to the reference](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.set_role).

**Comment by eltonfabricio10** [comment]
8db7d55f7b8742536f7cc7682f6279e980d3b2a5
