### ISSUE TITLE
MIME type

### ISSUE THREAD

**Issue by ezileicorreia** [biglinux/bigbashview#92]
BigBashView poderia ter uma extensão própria, por exemplo: .bbv ou .bbw, uma coisa simples que faz muita diferença e é legal demais ter.

**Comment by eltonfabricio10** [comment]
Explique mais a sua ideia, o que esta extensão faria?

**Comment by ezileicorreia** [comment]
Estive refletindo sobre a ideia e existe o inconveniente da nova extensão não ser reconhecida pelos editores de texto, que não estão cientes do BigBashView. Então, uma nova extensão, possivelmente não seria tão simples.
